"""
Step 2: Train YOLOv8 on Candlestick Pattern Dataset
Baseline target: ~89% accuracy (YOLOv8 benchmark from Vijayababu & Bennur 2023)
"""

import os
import yaml
import torch
from pathlib import Path
from ultralytics import YOLO

# ──────────────────────────────────────────────
# CONFIG
# ──────────────────────────────────────────────
DATA_DIR        = "./data"
RUNS_DIR        = "./runs"
MODEL_SIZE      = "yolov8s"      # n=nano, s=small, m=medium. Start with 's' for balance.
EPOCHS          = 50
IMAGE_SIZE      = 640
BATCH_SIZE      = 16             # Reduce to 8 if you get OOM errors
PATIENCE        = 10             # Early stopping patience
DEVICE          = "0" if torch.cuda.is_available() else "cpu"
PRETRAINED      = True           # Use ImageNet pretrained weights


def find_yaml(data_dir):
    """Locate the dataset YAML file auto-generated by Roboflow."""
    for f in Path(data_dir).rglob("*.yaml"):
        if "data" in f.name.lower() or f.stem in ["data", "dataset"]:
            return str(f)
    # fallback: grab any yaml
    yamls = list(Path(data_dir).rglob("*.yaml"))
    if yamls:
        return str(yamls[0])
    return None


def patch_yaml_paths(yaml_path):
    """
    Roboflow writes paths like '../train/images' relative to the YAML file.
    Rather than trusting those relative paths, we build correct absolute paths
    directly from DATA_DIR where we know the data was extracted.
    """
    with open(yaml_path, "r") as f:
        cfg = yaml.safe_load(f)

    data_root = Path(DATA_DIR).resolve()

    # Map Roboflow split names to folder names on disk
    split_map = {"train": "train", "val": "valid", "test": "test"}
    for key, folder in split_map.items():
        candidate = data_root / folder / "images"
        if candidate.exists():
            cfg[key] = str(candidate)
        elif key in cfg:
            # keep original if folder doesn't exist (e.g., no test split)
            raw = cfg[key]
            if raw and not os.path.isabs(raw):
                cfg[key] = str((Path(yaml_path).parent / raw).resolve())

    patched_path = str(Path(yaml_path).parent / "data_patched.yaml")
    with open(patched_path, "w") as f:
        yaml.dump(cfg, f)

    print(f"  train : {cfg.get('train')}")
    print(f"  val   : {cfg.get('val')}")
    print(f"  test  : {cfg.get('test')}")
    return patched_path


def train():
    print(f"\n{'='*60}")
    print("  YOLOv8 Candlestick Pattern Detector — Training")
    print(f"{'='*60}")
    print(f"  Device   : {DEVICE}")
    print(f"  Model    : {MODEL_SIZE}.pt")
    print(f"  Epochs   : {EPOCHS}")
    print(f"  Img size : {IMAGE_SIZE}")
    print(f"  Batch    : {BATCH_SIZE}")
    print(f"{'='*60}\n")

    # Locate dataset YAML
    yaml_path = find_yaml(DATA_DIR)
    if yaml_path is None:
        raise FileNotFoundError(
            f"No YAML file found in {DATA_DIR}. "
            "Did you run 1_download_dataset.py first?"
        )
    print(f"[*] Using dataset config: {yaml_path}")
    yaml_path = patch_yaml_paths(yaml_path)

    # Load model
    model_file = f"{MODEL_SIZE}.pt" if PRETRAINED else f"{MODEL_SIZE}.yaml"
    model = YOLO(model_file)
    print(f"[*] Loaded model: {model_file}")

    # Train
    results = model.train(
        data=yaml_path,
        epochs=EPOCHS,
        imgsz=IMAGE_SIZE,
        batch=BATCH_SIZE,
        patience=PATIENCE,
        device=DEVICE,
        project=RUNS_DIR,
        name="candlestick_yolov8",
        save=True,
        plots=True,
        # Augmentation — important for chart robustness across platforms
        hsv_h=0.015,
        hsv_s=0.3,
        hsv_v=0.2,
        flipud=0.0,   # Don't flip charts vertically (would invert candles!)
        fliplr=0.0,   # Don't flip horizontally (changes pattern meaning)
        mosaic=0.5,
        mixup=0.0,
    )

    # Save best model path for later scripts
    best_model = str(Path(RUNS_DIR) / "candlestick_yolov8" / "weights" / "best.pt")
    with open("./best_model_path.txt", "w") as f:
        f.write(best_model)

    print(f"\n[✓] Training complete.")
    print(f"    Best model saved to: {best_model}")
    return best_model


def validate(model_path):
    print(f"\n[*] Running validation on best model: {model_path}")
    model = YOLO(model_path)

    yaml_path = find_yaml(DATA_DIR)
    yaml_path = patch_yaml_paths(yaml_path)

    metrics = model.val(data=yaml_path, imgsz=IMAGE_SIZE, device=DEVICE)

    print(f"\n{'='*60}")
    print("  Validation Results")
    print(f"{'='*60}")
    print(f"  mAP50     : {metrics.box.map50:.4f}")
    print(f"  mAP50-95  : {metrics.box.map:.4f}")
    print(f"  Precision : {metrics.box.mp:.4f}")
    print(f"  Recall    : {metrics.box.mr:.4f}")
    print(f"{'='*60}\n")

    return metrics


if __name__ == "__main__":
    best_model_path = train()
    validate(best_model_path)
    print("Next step → run: python 3_extract_features.py")
